# Configuración general de la aplicación
spring.application.name=auth-service
server.port=8081

# Configuración de la Base de Datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/auth_db
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Configuración de JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000
